# Generated by Django 5.0.6 on 2024-06-10 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='YayinEvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=300)),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basim_yili', models.IntegerField()),
                ('resim', models.TextField()),
                ('kategori', models.ManyToManyField(to='magaza.kategori')),
                ('yayin_evi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magaza.yayinevi')),
                ('yazar', models.ManyToManyField(to='magaza.yazar')),
            ],
        ),
    ]
